# Python and Java rule sets pulled from https://github.com/feibaoBob/LLM-based_CAMD/blob/main/rule_source.py
rule_groups = {
	1: {
		'name': 'Use a Wildcard to Avoid Verification',
		'Message': 'Explicit Disabling of HTTPS Certificate Validation via HTTP Library Parameters. Characteristic: Directly setting validation toggle (e.g., verify=False) in high-level HTTP library calls, affecting only the current request - representing an application-layer convenience-style security bypass.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	2: {
		'name': 'Creating a Custom String to avoid Verification of Certificates',
		'Message': 'SSL secures HTTPS connections; overwriting Certificate Authority (CA) bundles to bypass certificate verification compromises security and enables MiTM attacks.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	3: {
		'name': 'Use an unverified context to avoid HTTPS Verification',
		'Message': 'Global Certificate Validation Bypass via Unverified SSL Context Creation. Characteristic: Constructing certificate-unverified SSL context objects (e.g., ssl._create_unverified_context()), reusable across multiple requests - representing a transport-layer infrastructure-level security flaw.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	4: {
		'name': 'Using HTTP instead of HTTPS',
		'Message': 'Developers should access APIs/web services via HTTPS (not HTTP) for SSL confidentiality; HTTP compromises security as per Wildcard Misuse Pattern',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	5: {
		'name': 'Using Insecure Random Number Generation',
		'Message': 'Insecure keys enable attackers to compromise encryption. Cryptographically strong randomness is essential. In Python, using random module for keys (salts) generation is insecure, the secrets module provides cryptographically secure alternatives.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	6: {
		'name': 'Using a static and insecure Salt',
		'Message': 'Password-Based Encryption (PBE) requires cryptographically secure random salts; predictable salts enable dictionary attacks and compromise encryption.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	7: {
		'name': 'Using an Insecure Mode',
		'Message': 'While developers may choose different algorithms for their encryption, they may choose the Electronic Codebook (ECB) mode. This mode is insecure as it breaks integrity and may leak information. It is recommended to use different modes such as Cipher Block Chaining (CBC)',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	8: {
		'name': 'Using less than 1000 Iterations',
		'Message': 'Password-Based Encryption (PBE) requires iteration counts ≥1000; lower values enable brute-force attacks and violate Python security standards.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	9: {
		'name': 'Using Insecure Block Ciphers',
		'Message': 'Ciphers such as Data Encryption Standard (DES) are considered insecure. Should use the secure symmetric cipher Advanced Encryption Standard (AES). However, The use of non-randomly generated keys, insecure encryption modes (such as ECB), or fixed/predictable initialization vectors (IVs) in AES are also considered insecure.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	10: {
		'name': 'Using an Insecure Asymmetric Cipher',
		'Message': 'Asymmetric encryption requires public/private keys for confidentiality and integrity; Example: RSA/DSA must use ≥2048-bit keys to remain cryptographically secure',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "C/A",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	 },
	11: {
		'name': 'Using an insecure Hash',
		'Message': 'Developers use cryptographic hashes (like SHA256 or SHA512) to verify message or file integrity by generating a unique digest. Broken hashes like MD2, MD4, MD5, and SHA1 are insecure because different inputs can produce the same digest, compromising integrity.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	12: {
		'name': 'Not verifying the Json Web Token (JWT)',
		'Message': 'JWT enable compact authentication but must retain default signature verification; disabling verification fundamentally compromises security.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	13: {
		'name': 'Using a deprecated or invalid Transport Layer Security (TLS) Version',
		'Message': 'Must avoid insecure/deprecated TLS/SSL versions; these enable MiTM attacks—use only latest versions.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	14: {
		'name': 'Using an Insecure Protocol',
		'Message': 'When connecting to certain systems or computers, developers can use the Lightweight Directory Access Protocol (LDAP) protocol. Developers may connect using LDAP without providing credentials, which allows unauthenticated connections. To ensure a confidential connection, it is recommended to provide credentials.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	15: {
		'__link__': 'https://docs.python.org/3/library/xml.html#xml-vulnerabilities',
		'name': 'Using an insecure XML Deserialization',
		'Message': 'Using an Insecure Extensible Markup Language (XML) Deserialization. Developers who use XML objects should use secure methods to protect against Server-Side Request Forgery (SSRF) attacks. SSRF attacks will allow attackers to read the configuration information about the server. It is recommended for developers to disable network access and resolve remote entities.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Integrity",
		"Attack Type": "Deserialization",
		"Analysis Method": ""
	},
	16: {
		'__link__': 'LINK',
		'name': 'Using an insecure YAML Deserialization',
		'Message': 'YAML modules may be exploited in a similar way to the XML Deserialization Misuse pattern. Unsafe usage of YAML grants attackers access to Remote Code Execution (RCE) by simple deserialization. Each YAML module has a safe deserialization method that is recommended.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Integrity",
		"Attack Type": "Deserialization",
		"Analysis Method": ""
	},
	17: {
		'__link__': 'https://docs.python.org/3/library/pickle.html#restricting-globals',
		'name': 'Using an Insecure Pickle Deserialization',
		'Message': 'The Pickle format is inherently insecure and enables Remote Code Execution; avoid entirely, but if required, sign files for integrity verification.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Deserialization",
		"Analysis Method": ""
	},
	18: {
		'__link__': 'https://rules.sonarsource.com/python/type/Vulnerability/RSPEC-2631',
		'name': 'Not properly escaping regular expressions (regex)',
		'Message': 'Developers who use regex should escape the input they pass in to avoid Denial of Service (DoS). If they do not escape regular expressions, the input passed can cause the computer to calculate the expression continuously. It is recommended to escape the input to better sanitize the input passed in the regular expression engine.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	-1: {
		'name': 'UNKNOWN',
		'Message': 'UNKNOWN',
		'CWE': 'UNKNOWN',
		'Severity': "UNKNOWN",
		"Crypto Property": "UNKNOWN",
		"Attack Type": "UNKNOWN",
		"Analysis Method": "UNKNOWN"
	},
}

rule_groups_java = {
	1: {
		'name': 'Cryptographic keys',
		'Message': 'Cryptographic keys must be unpredictable when using SecretKeySpec (byte array input). Hardcoded/constant byte arrays expose keys, enabling adversaries to access sensitive data. Generate unpredictable byte arrays for secure keys instead.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Predictable Secrets",
		"Analysis Method": ""
	},
	2: {
		'name': 'Passwords in Password-based Encryption (PBE)',
		'Message': 'PBE keys generated via PBEKeySpec require three parameters: password, salt, and iteration count. Hardcoded/constant passwords expose keys, enabling attackers to predict keys. Use unpredictable passwords in PBEKeySpec instead.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Predictable Secrets",
		"Analysis Method": ""
	},
	3: {
		'name': 'Passwords in KeyStore',
		'Message': 'KeyStore passwords (via java.security.KeyStore) protect stored keys/certificates. Hardcoded/constant passwords risk exposure of all secured items. Use unpredictable passwords to access the KeyStore instead.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Predictable Secrets",
		"Analysis Method": ""
	},
	4: {
		'name': 'Hostname Verifier',
		'Message': 'Hostname verification via HostnameVerifier.verify() must perform actual checks. Returning true by default enables URL spoofing, facilitating attacks like phishing.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	5: {
		'name': 'Certificate Validation',
		'Message': 'Certificate validation via X509TrustManager must implement proper checks. Empty validation methods trust all certificates, including untrusted ones, enabling Man-in-the-middle (MitM) attacks. ',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	6: {
		'name': 'SSL Sockets',
		'Message': 'SSL socket connections via SSLSocket require hostname verification (using HostnameVerifier). Omitting verification during socket creation enables insecure connections.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	7: {
		'name': 'Hypertext Transfer Protocol',
		'Message': 'When using java.net.URL, never employ HTTP for sensitive data transmission; always use HTTPS to prevent interception of unencrypted information.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	8: {
		'name': 'Pseudorandom Number Generator (PRNG)',
		'Message': 'When generating random values for cryptographic operations, never use java.util.Random; always employ java.security. SecureRandom to prevent predictable random values.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	9: {
		'name': 'Seeds in Pseudorandom Number Generator (PRNG)',
		'Message': 'PRNG seeding in SecureRandom must use non-deterministic seeds. Constant/static seeds cause predictable outputs on every run, creating security risks. Use random seeds instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	10: {
		'name': 'Salts in Password-based encryption (PBE)',
		'Message': 'PBE salts (via PBEParameterSpec) must be randomly generated. Constant/static salts enable dictionary attacks, producing predictable keys. Use cryptographically random salts instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	11: {
		'name': 'Mode of Operation',
		'Message': 'Cipher modes in javax.crypto.Cipher: ECB is insecure due to plaintext pattern leakage. Use CBC or GCM instead. ',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	12: {
		'name': 'Initialization Vector (IV)',
		'Message': 'Initialization Vectors (IVs) enhance cryptographic security when used with secret keys. Static/constant IVs introduce vulnerabilities by reducing randomness. Use unpredictable random IVs via IvParameterSpec instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	13: {
		'name': 'Iteration Count in Password-based Encryption (PBE)',
		'Message': 'When configuring PBEParameterSpec, always set iteration counts above 1000 to ensure sufficient resistance against brute-force attacks.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	14: {
		'name': 'Symmetric Ciphers',
		'Message': 'Symmetric ciphers use the same key for encryption and decryption. 64-bit ciphers (DES, Blowfish, RC4, RC2, IDEA) are broken due to feasible brute-force attacks and are insecure. AES (128-bit block size, 128/192/256-bit keys) should be used for security.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	15: {
		'name': 'Asymmetric Ciphers',
		'Message': 'Asymmetric ciphers use public/private key pairs. 1024-bit RSA is broken due to feasible brute-force attacks. Always use ≥2048-bit keys for RSA security.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "C/A",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	16: {
		'name': 'Cryptographic Hash Functions',
		'Message': 'Cryptographic hash functions convert arbitrary input to a fixed-length hash. Broken functions (SHA1, MD4, MD5, MD2) are vulnerable to collisions (same hash for different inputs), causing security risks. Developers must use strong alternatives like SHA-256.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	17: {
		'name': 'Cryptographic MAC',
		'Message': 'When implementing MAC algorithms, never use HmacMD5 or HmacSHA1; always employ HmacSHA256+ to prevent collision-based forgery attacks.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	18: {
		'name': 'Credentials in String',
		'Message': 'When handling sensitive credentials, never store them in String variables; always use mutable char/byte arrays and clear immediately after use to prevent memory exposure.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-force",
		"Analysis Method": ""
	},
	-1: {
		'name': 'UNKNOWN',
		'Message': 'UNKNOWN',
		'CWE': 'UNKNOWN',
		'Severity': "UNKNOWN",
		"Crypto Property": "UNKNOWN",
		"Attack Type": "UNKNOWN",
		"Analysis Method": "UNKNOWN"
	},
}

# Derived from 
# Automatic Detection of Go Cryptographic API Misuses
# Gopher (CryDict)
# Evaluating Cryptographic API Misuse Detectors for Go
rule_groups_go = {
	1: {
		'name': 'Using Insecure Random Number Generation',
		'Message': 'Using math/rand for keys, tokens, or nonces produces predictable output because it is not cryptographically secure. crypto/rand must be used for any security-sensitive random value.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	2: {
		'name': 'Using Hardcoded or Constant Cryptographic Keys',
		'Message': 'Passing a static/constant byte slice as a key to aes.NewCipher, hmac.New, or similar constructors exposes the key in source and binary, letting an attacker who reads either fully recover it.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Predictable Secrets",
		"Analysis Method": ""
	},
	3: {
		'name': 'Using a Predictable or Static Initialization Vector (IV)',
		'Message': 'Supplying a fixed or all-zero IV to cipher.NewCBCEncrypter, cipher.NewCTR, or cipher.NewGCM defeats semantic security: identical plaintexts under the same key produce identical ciphertexts.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	4: {
		'name': 'Using a Static or Predictable Salt in Key Derivation',
		'Message': 'Password-based key derivation (pbkdf2.Key, scrypt.Key, argon2) requires a random, per-use salt. A constant or reused salt lets attackers precompute dictionary/rainbow-table attacks across derived keys.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	5: {
		'name': 'Using an Insecure Block Cipher Mode (ECB)',
		'Message': 'Electronic Codebook (ECB) mode encrypts identical plaintext blocks to identical ciphertext blocks, leaking structural information. CBC or GCM should be used instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	6: {
		'name': 'Using Fewer than 1000 Iterations in Password-Based Key Derivation',
		'Message': 'pbkdf2.Key (and similar) iteration counts below 1000 make brute-force and dictionary attacks against the derived key computationally cheap.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	7: {
		'name': 'Using Insecure or Deprecated Symmetric Ciphers',
		'Message': 'The des and rc4 packages implement ciphers (DES, 3DES, RC4) that are broken or brute-forceable with modern hardware. AES should be used instead, per NIST SP 800-57 tiering.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	8: {
		'name': 'Using an Insecure Asymmetric Key Size',
		'Message': 'rsa.GenerateKey called with a modulus below 2048 bits produces keys that are feasible to factor with current computing resources.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "C/A",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	9: {
		'name': 'Using an Insecure Hash Function',
		'Message': 'The md5 and sha1 packages are broken for collision resistance. sha256 or stronger must be used wherever a digest is relied on for integrity.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	10: {
		'name': 'Disabling TLS Certificate Verification',
		'Message': 'Setting tls.Config{InsecureSkipVerify: true} disables server certificate validation entirely, allowing any attacker positioned on the network path to impersonate the server.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	11: {
		'name': 'Using a Deprecated or Invalid TLS Version',
		'Message': 'Configuring tls.Config with MinVersion set to SSL3.0/TLS1.0/TLS1.1 permits protocol-downgrade attacks; only TLS 1.2+ should be allowed.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	12: {
		'name': 'Using a Predictable PRNG Seed',
		'Message': 'Calling math/rand.Seed() with a constant or low-entropy value (e.g. a fixed integer, or time.Now().Unix() alone) makes every subsequent "random" value in the sequence predictable.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	-1: {
		'name': 'UNKNOWN',
		'Message': 'UNKNOWN',
		'CWE': 'UNKNOWN',
		'Severity': "UNKNOWN",
		"Crypto Property": "UNKNOWN",
		"Attack Type": "UNKNOWN",
		"Analysis Method": "UNKNOWN"
	},
}

# Rule set pulled from JScamd
rule_groups_js = {
	1: {
		'name': 'Using Insecure Random Number Generation',
		'Message': 'Math.random() is not cryptographically secure and must not be used to generate keys, tokens, or nonces. crypto.randomBytes() or crypto.getRandomValues() should be used instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	2: {
		'name': 'Using Hardcoded or Constant Cryptographic Keys',
		'Message': 'Passing a static string or Buffer literal as the key argument to crypto.createCipheriv or crypto.createHmac exposes the key to anyone who reads the source, fully compromising confidentiality.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Predictable Secrets",
		"Analysis Method": ""
	},
	3: {
		'name': 'Using a Predictable or Static Initialization Vector (IV)',
		'Message': 'Supplying a fixed or all-zero IV (e.g. Buffer.alloc(16, 0)) to crypto.createCipheriv defeats semantic security: identical plaintexts under the same key produce identical ciphertexts.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	4: {
		'name': 'Using a Static or Predictable Salt in Key Derivation',
		'Message': 'crypto.pbkdf2/pbkdf2Sync and scrypt require a random, per-use salt. A constant or reused salt lets attackers precompute dictionary/rainbow-table attacks across derived keys.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	5: {
		'name': 'Using Fewer than 1000 Iterations in Password-Based Key Derivation',
		'Message': 'crypto.pbkdf2/pbkdf2Sync iteration counts below 1000 make brute-force and dictionary attacks against the derived key computationally cheap.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	6: {
		'name': 'Using an Insecure Block Cipher Mode (ECB)',
		'Message': 'Passing an ECB algorithm string (e.g. "aes-128-ecb") to crypto.createCipheriv encrypts identical plaintext blocks to identical ciphertext blocks, leaking structural information.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	7: {
		'name': 'Using the Deprecated crypto.createCipher()/createDecipher() API',
		'Message': 'createCipher/createDecipher derive the key and IV from a passphrase using a single unsalted MD5 pass (EVP_BytesToKey), which is weak and deprecated. createCipheriv with an explicit random key and IV should be used instead.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Confidentiality",
		"Attack Type": "CPA",
		"Analysis Method": ""
	},
	8: {
		'name': 'Using Insecure or Deprecated Symmetric Ciphers',
		'Message': 'Algorithm strings selecting DES, 3DES, or RC4 in crypto.createCipheriv are broken or brute-forceable with modern hardware. AES should be used instead.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "Confidentiality",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	9: {
		'name': 'Using an Insecure Asymmetric Key Size',
		'Message': 'crypto.generateKeyPair("rsa", { modulusLength: ... }) called with a modulus below 2048 bits produces keys that are feasible to factor with current computing resources.',
		'CWE': '',
		'Severity': "L",
		"Crypto Property": "C/A",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	10: {
		'name': 'Using an Insecure Hash Function',
		'Message': 'crypto.createHash("md5") and crypto.createHash("sha1") are broken for collision resistance. sha256 or stronger must be used wherever a digest is relied on for integrity.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Brute-Force",
		"Analysis Method": ""
	},
	11: {
		'name': 'Disabling TLS Certificate Validation',
		'Message': 'Setting rejectUnauthorized: false on https/tls request options (or NODE_TLS_REJECT_UNAUTHORIZED=0) disables server certificate validation, allowing any attacker on the network path to impersonate the server.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	12: {
		'name': 'Using HTTP instead of HTTPS',
		'Message': 'Using the http module (or an "http://" URL with fetch) to transmit sensitive data leaves it unencrypted on the wire; https should be used instead.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "C/I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	13: {
		'name': 'Using a Deprecated or Invalid TLS Version',
		'Message': 'Configuring tls.connect with secureProtocol set to an SSLv3/TLSv1/TLSv1.1 method, or minVersion below "TLSv1.2", permits protocol-downgrade attacks.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Confidentiality",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	14: {
		'name': 'Disabling or Weakening JSON Web Token (JWT) Verification',
		'Message': 'Calling jsonwebtoken.verify() with algorithms including "none", or using jwt.decode() in place of jwt.verify(), accepts tokens without checking their signature, letting an attacker forge arbitrary claims.',
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "I/A",
		"Attack Type": "SSL/TLS MitM",
		"Analysis Method": ""
	},
	15: {
		'name': 'Using an Insecure Deserialization',
		'Message': "Passing untrusted input to node-serialize's unserialize(), or to eval()/vm.runInContext(), allows an attacker to embed executable code in the serialized payload and achieve Remote Code Execution.",
		'CWE': '',
		'Severity': "H",
		"Crypto Property": "Integrity",
		"Attack Type": "Deserialization",
		"Analysis Method": ""
	},
	16: {
		'name': 'Using Predictable Session or Token Generation',
		'Message': 'Generating session identifiers or auth tokens from Math.random() or a non-cryptographic UUID (e.g. uuid v1, which encodes MAC address and timestamp) instead of crypto.randomUUID()/crypto.randomBytes() makes them guessable.',
		'CWE': '',
		'Severity': "M",
		"Crypto Property": "Randomness",
		"Attack Type": "Predictability",
		"Analysis Method": ""
	},
	-1: {
		'name': 'UNKNOWN',
		'Message': 'UNKNOWN',
		'CWE': 'UNKNOWN',
		'Severity': "UNKNOWN",
		"Crypto Property": "UNKNOWN",
		"Attack Type": "UNKNOWN",
		"Analysis Method": "UNKNOWN"
	},
}

# General misuse rules derived from MASC and Automatic Generation of a Cryptography Misuse Taxonomy
rule_groups_general = {
	1: {
		'name': 'Using an Insufficient Public-Key Size',
		'Message': 'RSA keys under 2048 bits, or elliptic-curve keys under 224 bits, are within reach of modern factoring/discrete-log attacks. Generate asymmetric keys at or above these sizes regardless of which language or library performs the key generation.',
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'C/A',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #1, #2, #3',
	},
	2: {
		'name': 'Using Insecure RSA Padding or an RSA Cipher Mode',
		'Message': 'Encrypting directly with RSA and no padding, using legacy PKCS#1 v1.5 padding for encryption (as opposed to signatures), or wrapping RSA in a block-cipher mode of operation, are all constructions with known practical attacks (e.g. Bleichenbacher-style padding oracles). Use RSA-OAEP or an equivalent modern padding scheme instead.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Padding Oracle',
		'Analysis Method': '',
		'__source__': 'MASC #4, #5, #6',
	},
	3: {
		'name': 'Using a Weak or Deprecated SSL/TLS Protocol Version',
		'Message': 'Requesting a generic "SSL" context, or explicitly negotiating SSLv2, SSLv3, or TLS below 1.2, allows a connection to be downgraded to a version with known breaks (POODLE, BEAST, etc.). Pin the minimum protocol version to TLS 1.2 or higher in whatever TLS API the language exposes.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #7, #8, #9, #10, #14, #15',
	},
	4: {
		'name': 'Negotiating a Weak Cipher Suite or MAC Inside TLS',
		'Message': 'Allowing HMAC-SHA1 or HMAC-MD5 as the TLS integrity check, or allowing non-authenticated CBC-mode cipher suites, weakens the channel even when the protocol version itself is modern. Restrict the cipher suite list to AEAD suites (e.g. AES-GCM, ChaCha20-Poly1305) with a strong MAC.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #11, #12, #13',
	},
	5: {
		'name': 'Performing a Key Exchange Without Entity Authentication',
		'Message': 'An unauthenticated key exchange (e.g. anonymous Diffie-Hellman) establishes a shared secret with whoever answers, not necessarily the intended party, making it trivially interceptable by an active attacker. Always bind the key exchange to a verified identity (certificate, pre-shared key, or signed exchange).',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #31',
	},
	6: {
		'name': 'Using an Insufficient Symmetric Key Size',
		'Message': 'AES keys under 128 bits, RC2 keys under 64 bits, or Blowfish keys under 128 bits are small enough to be brute-forced with modern hardware. Use a full-strength key size for whichever symmetric cipher the codebase selects.',
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #71, #72, #73',
	},
	7: {
		'name': 'Using an Insecure Block Cipher Mode (ECB, or Unauthenticated CBC)',
		'Message': "Electronic Codebook (ECB) mode always encrypts identical plaintext blocks to identical ciphertext blocks, leaking structural information about the plaintext, and it is a common insecure default: several languages' crypto libraries silently fall back to ECB when a mode is not explicitly requested. CBC mode used without a separate MAC (or without an AEAD construction like GCM) also fails to protect integrity, enabling padding-oracle and bit-flipping attacks. Always pick an authenticated mode (GCM, ChaCha20-Poly1305) or pair CBC with an HMAC explicitly.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'CPA',
		'Analysis Method': '',
		'__source__': 'MASC #40, #76, #77, #78, #79, #80, #81, #82, #83',
	},
	8: {
		'name': 'Using a Predictable, Static, Zeroed, or Reused Initialization Vector (IV)',
		'Message': 'An IV that is hardcoded, all-zero, reused across messages under the same key, or derived from a predictable source (a filename, a timestamp, or the plaintext itself) breaks the semantic-security guarantee of CBC/CTR/GCM: identical or related plaintexts leak a relationship in their ciphertexts. Generate a fresh, unpredictable IV/nonce for every encryption operation.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'CPA',
		'Analysis Method': '',
		'__source__': 'MASC #84, #86, #87, #98',
	},
	9: {
		'name': 'Using a Broken or Deprecated Symmetric Cipher Algorithm',
		'Message': 'DES, 3DES/DESede, RC2, RC4, Blowfish, IDEA, SEED, export-grade ciphers (e.g. the historical EXP1024 tier), a no-op/identity cipher, and legacy stream ciphers like RC5 are all either brute-forceable with modern hardware or have known structural breaks. Standardize on AES (or another NIST/ISO-vetted modern cipher) instead.',
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #88, #89, #90, #91, #92, #93, #95, #96, #106; CryMisTa 5.3.1 (insecure RC5 usage)',
	},
	10: {
		'name': 'Reusing a Key or Nonce Across Multiple Encryption Operations',
		'Message': 'Reusing a stream-cipher key across multiple messages, or reusing a nonce with the same key in an AEAD mode such as GCM, lets an attacker XOR two ciphertexts to cancel out the keystream (stream ciphers) or fully recover the authentication key (GCM). This is one of the most damaging cryptographic mistakes because it can be catastrophic rather than merely weakening. Never reuse a key/nonce pair; derive a new nonce (or rotate the key) for every message.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Nonce Reuse',
		'Analysis Method': '',
		'__source__': 'MASC #97; CryMisTa 5.3.3 (insecure nonce reuse)',
	},
	11: {
		'name': 'Using Insecure Authenticated-Encryption (AEAD) Parameters',
		'Message': 'Truncating the GCM authentication tag below its recommended length, using a GCM IV length outside the supported/validated range, or deriving the GCM IV from a predictable source (including the key itself) all weaken or defeat the integrity guarantee that AEAD modes exist to provide. Follow NIST SP 800-38D for tag length, IV length, and IV generation when using GCM (or the equivalent guidance for the AEAD mode in use).',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Forgery',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.2 (inappropriate GCM tag length; insecure/unsupported GCM IV length; predictable GCM IV source; insecure XTS tweak calculation)',
	},
	12: {
		'name': 'Using Stateless or IV-less Encryption',
		'Message': 'Encrypting without tracking any per-message state (no IV, no counter, no nonce) forces every message to be encrypted identically under a given key, which is functionally equivalent to ECB even if the underlying mode is not ECB. Every encryption call needs a unique IV/nonce, tracked across calls.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'CPA',
		'Analysis Method': '',
		'__source__': 'MASC #107',
	},
	13: {
		'name': 'Using an Insufficient Iteration Count in Password-Based Key Derivation',
		'Message': "A low iteration count in PBKDF2 (or an equivalent work-factor parameter in scrypt/Argon2) makes brute-forcing every candidate password cheap. The historically-cited floor of 1,000 iterations is itself outdated: current guidance (e.g. OWASP's 600,000-iteration recommendation for PBKDF2-HMAC-SHA256, as of 2023) is far higher, so a rule that only flags counts under 1,000 will miss most real-world weak configurations. Use current guidance for the specific KDF and hash in use, not a fixed historical number.",
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #74, #75; CryMisTa 5.3.1 (outdated PBKDF2 iteration-count baseline)',
	},
	14: {
		'name': 'Using a Static, Constant, or Missing Salt',
		'Message': 'Deriving a key or hashing a password without a salt, or with a hardcoded/shared salt, lets an attacker precompute a dictionary or rainbow-table attack that works across every user or every run. Generate a fresh random salt per password/key and store it alongside the derived value.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'CPA',
		'Analysis Method': '',
		'__source__': 'MASC #57, #63, #85',
	},
	15: {
		'name': 'Using a Weak Hash Function Inside a Key Derivation Function',
		'Message': "Building a password-based key derivation function on top of MD5, MD2, or anything weaker than SHA-224 inherits that hash's collision and speed weaknesses, undermining the KDF's brute-force resistance even if the iteration count is otherwise reasonable. Use SHA-256 or stronger as the KDF's underlying hash.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #56, #58, #59',
	},
	16: {
		'name': 'Using a Hardcoded or Constant Cryptographic Key',
		'Message': 'A key baked into source code or configuration as a literal value is exposed to anyone who can read the source, decompile the binary, or find it in version control, fully compromising every message it protects. Keys must be generated at runtime or loaded from a secrets manager/HSM, never written as a constant.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Predictable Secrets',
		'Analysis Method': '',
		'__source__': 'MASC #61, #62',
	},
	17: {
		'name': 'Using Low-Entropy or Predictable Key Material',
		'Message': 'Seeding key generation from a low-entropy source (a short passphrase treated as raw key bytes, a counter, predictable environment data) produces keys that fall within a search space small enough to brute-force, even though the key itself is not literally hardcoded. Feed key generation only from a cryptographically secure RNG with sufficient entropy.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Predictability',
		'Analysis Method': '',
		'__source__': 'MASC #55, #60',
	},
	18: {
		'name': 'Using a Key Past Its Expiration Date',
		'Message': 'Continuing to encrypt, sign, or authenticate with a key after its designated rotation/expiration date extends the window an attacker has to compromise that single key and defeats whatever rotation policy the system was designed around. Enforce key expiration and rotate on schedule.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Key Compromise',
		'Analysis Method': '',
		'__source__': 'MASC #29',
	},
	19: {
		'name': 'Insecure Handling of Secrets in Memory',
		'Message': "Holding a key, password, or plaintext secret only in an immutable value type (an ordinary string in most languages) means it cannot be reliably overwritten/zeroed once no longer needed, so it can linger in memory, swap files, or crash dumps long after use, and is also more likely to be accidentally logged. Store secrets in a mutable byte buffer and explicitly clear it once you're done, in whatever language you're working in.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Memory Disclosure',
		'Analysis Method': '',
		'__source__': 'MASC #48, #51; CryMisTa 5.3.8 (improper cleanup of cryptographic key material)',
	},
	20: {
		'name': 'Insecure Private-Key or Encryption-Key Storage',
		'Message': 'Persisting a private key or encryption key to disk, a config file, or a database column without encryption-at-rest, file-permission restrictions, or a dedicated key-management service turns any file-read vulnerability elsewhere in the system into a full key compromise. Store long-lived key material in a keystore, vault, or HSM designed for the purpose.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Key Compromise',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (insecure private key storage/handling; insecure storage of encryption keys)',
	},
	21: {
		'name': 'Using a Non-Cryptographic PRNG for Security-Sensitive Values',
		'Message': "A general-purpose pseudo-random number generator (the kind meant for simulations, shuffling, or test data) is designed for statistical quality, not unpredictability against an adversary who studies its algorithm: its output can often be predicted after observing only a few values. Use the language's cryptographically secure RNG for anything security-sensitive (keys, tokens, nonces, salts).",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Randomness',
		'Attack Type': 'Predictability',
		'Analysis Method': '',
		'__source__': 'MASC #101',
	},
	22: {
		'name': 'Seeding a Secure RNG with a Static or Predictable Value',
		'Message': 'Even a cryptographically secure RNG becomes predictable if it is explicitly (re-)seeded with a constant, a low-entropy value, or a value derived from something an attacker can guess or observe (like the current time alone): every output after that point is then reproducible by anyone who guesses the seed. Let the secure RNG self-seed from the OS entropy source; avoid calling its seed function manually.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Randomness',
		'Attack Type': 'Predictability',
		'Analysis Method': '',
		'__source__': 'MASC #100, #102',
	},
	23: {
		'name': 'Deriving Randomness from a Low-Entropy or Unsuitable Source',
		'Message': 'Building "randomness" out of a source that was never designed to be unpredictable, such as a non-cryptographic checksum algorithm like adler32, a file\'s metadata, or other low-entropy input, produces values with far less real entropy than they appear to have. Only use a source explicitly documented as cryptographically secure for anything randomness-dependent.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Randomness',
		'Attack Type': 'Predictability',
		'Analysis Method': '',
		'__source__': 'MASC #99; CryMisTa 5.3.1 (adler32 used as a randomness source)',
	},
	24: {
		'name': 'Using a Broken Hash Algorithm for Credentials or Integrity (MD2/MD4/MD5)',
		'Message': "MD2, MD4, and MD5 all have practical collision attacks published, meaning two different inputs can be crafted to produce the same digest: fatal for anything that relies on a hash to prove a credential or a file wasn't tampered with. Use SHA-256 or stronger wherever a digest needs to resist deliberate collisions.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #64, #65, #66',
	},
	25: {
		'name': 'Using SHA-1 for Hashing Credentials',
		'Message': 'SHA-1 has demonstrated, practical collision attacks (e.g. the "SHAttered" attack) and is deprecated by essentially every standards body for security use. Move credential hashing to SHA-256 or a purpose-built password hash (bcrypt, scrypt, Argon2).',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #68',
	},
	26: {
		'name': 'Using an Obsolete or Deprecated Hash Algorithm',
		'Message': 'Beyond the specifically-named broken hashes, standards bodies periodically deprecate entire algorithms (or specific parameter choices within them) as cryptanalysis advances. Treat "deprecated by NIST/vendor documentation" as disqualifying on its own, independent of whether a public collision attack yet exists.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #67',
	},
	27: {
		'name': 'Implementing a Custom Digest Instead of Using a Standard One',
		'Message': 'A hand-rolled hashing routine has not been through the years of public cryptanalysis that standard algorithms have, so its collision- and preimage-resistance are unproven: "we wrote our own" is a red flag on its own regardless of how it works internally. Use a vetted standard library implementation (SHA-256/3, BLAKE2/3) instead of a custom digest function.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'MASC #70',
	},
	28: {
		'name': "Using a Modern Hash Primitive's Insecure Legacy Variant",
		'Message': 'Some modern primitives shipped an early, non-standardized variant before the final specification was ratified; for example, early Keccak implementations used a different padding scheme than the NIST-standardized SHA-3 (FIPS 202). Calling the legacy/pre-standard variant (e.g. a "legacy Keccak-256" function) instead of the standardized one can silently produce a non-interoperable or weaker construction. Always call the standardized function name/parameters for whichever modern primitive is in use.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.1 (legacy Keccak256 padding vs. NIST FIPS 202 SHA-3)',
	},
	29: {
		'name': 'Using a Weak Hash Algorithm for Digital Signatures',
		'Message': "Signing over an MD2, MD4, MD5, or SHA-1 digest inherits that hash's collision weaknesses, letting an attacker potentially craft two different documents with the same signature. Sign over a SHA-256 (or stronger) digest.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Forgery',
		'Analysis Method': '',
		'__source__': 'MASC #25, #26, #27, #28',
	},
	30: {
		'name': 'Insufficient Validation of Signature or Public-Key Parameters',
		'Message': "Verifying a signature (e.g. with an RSA-based scheme) without checking the signature size and the strength of the public key used to make it can let a forged or degenerate signature pass verification. Validate both the key strength and the signature's structural parameters before trusting a verification result, per the signature scheme's specification (e.g. RFC 3447).",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Forgery',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.10 (potential misuse of signature function, lack of input validation)',
	},
	31: {
		'name': 'Mixing HTTP and HTTPS for the Same Sensitive Data Flow',
		'Message': 'Loading a page, API response, or resource partly over HTTP and partly over HTTPS (mixed content) exposes the HTTP portion to interception and tampering even though the "main" connection is encrypted, and can be used to strip protection from the whole flow. Serve every request in a sensitive flow over HTTPS, with no HTTP fallback.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #30',
	},
	32: {
		'name': 'Improper or Missing Certificate Revocation Checking',
		'Message': "Accepting a certificate without checking whether it has been revoked (via OCSP or a CRL) means a certificate known to be compromised, expired early, or issued in error will still be trusted. Wire up revocation checking wherever the platform's TLS stack supports it, and fail closed when a check cannot be completed.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #32',
	},
	33: {
		'name': 'Improper Hostname/Certificate Validation',
		'Message': "Accepting a certificate whose subject/SAN does not match the hostname actually being connected to defeats the entire point of the certificate: it proves identity for a different server. Verify the presented certificate's hostname against the address being connected to on every connection, using the platform's standard verification routine rather than a hand-rolled comparison.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #33',
	},
	34: {
		'name': 'Trusting an Untrusted, Unpinned, or Self-Signed Certificate',
		'Message': 'Accepting any certificate signed by an untrusted or self-signed CA, or accepting any certificate at all in the absence of pinning where pinning is expected, allows an attacker who can present any certificate (including one they minted themselves) to impersonate the server. Verify the certificate chain against a trusted root, and pin the expected certificate/public key where the threat model calls for it.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #34, #104; CryMisTa 5.3.7 (lack of public key pinning; hardcoded certificate)',
	},
	35: {
		'name': 'Certificate Lifetime Misconfiguration',
		'Message': 'A TLS certificate valid for an excessively long period increases the damage window if its key is ever compromised, since revocation is the only remaining defense; a certificate valid for an excessively short period instead forces frequent, error-prone renewal that risks outages when renewal fails. Follow current CA/Browser Forum and NIST guidance (e.g. NIST SP 800-52/1800-16) on certificate lifetimes rather than picking an arbitrary duration.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.7 (long-lived certificates; short certificate validity period)',
	},
	36: {
		'name': 'Disabling Host-Key Verification for a Trust-on-First-Use Protocol',
		'Message': 'Protocols like SSH authenticate the server by a known host key rather than a CA-signed certificate; explicitly disabling that check (e.g. an "ignore host key" option) accepts a connection to any server, defeating the protocol\'s only server-authentication mechanism. Verify the host key against a known-hosts list or equivalent, and never disable that check outside of throwaway test environments.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (disabling SSH host-key verification)',
	},
	37: {
		'name': 'Using an Unencrypted Socket for Sensitive Data',
		'Message': 'Opening a plain TCP/UDP socket (no TLS) to send credentials, tokens, or other sensitive data leaves that traffic readable and modifiable by anyone on the network path. Wrap the socket in TLS, or use a library/protocol that provides it, whenever sensitive data crosses the connection.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'SSL/TLS MitM',
		'Analysis Method': '',
		'__source__': 'MASC #50, #105',
	},
	38: {
		'name': 'Embedding Authentication Tokens in URLs',
		'Message': 'Passing a bearer token as a URL query parameter causes it to be logged by web servers, proxies, and browser history, and leaked via the Referer header to any linked third-party resource. Send tokens in a header (e.g. Authorization) or request body instead, per RFC 6750.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Token Leakage',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.6 (insecure usage of encryption tokens)',
	},
	39: {
		'name': 'Generating Tokens from Insufficient Secret Material',
		'Message': 'A session or API token generated with too little underlying entropy (a short random string, a predictable counter, or a weak hash of guessable inputs) is vulnerable to brute-force guessing even though it "looks" random. Follow NIST SP 800-63 guidance on minimum token length/entropy for the security level required.',
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Brute-Force',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.6 (insecure use of secrets for token generation)',
	},
	40: {
		'name': 'Insufficient Token Expiration or Missing Expiry Error Handling',
		'Message': 'Issuing tokens with an excessively long lifetime, or failing to reject/handle an expired token cleanly, extends how long a leaked token remains useful to an attacker. Set a short, use-case-appropriate expiration and make sure expired-token handling actually rejects the request, per NIST SP 800-63.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'I/A',
		'Attack Type': 'Token Replay',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.6 (insufficient token expiration and lack of proper error handling)',
	},
	41: {
		'name': 'Insecure One-Time-Password (OTP) Expiration Logic',
		'Message': "A bug in how an OTP's validity window is computed or enforced (off-by-one errors, clock-skew handling, or a window left open after use) can let an OTP be replayed or accepted long after it should have expired. Verify OTP expiration and single-use enforcement match NIST SP 800-63 guidance exactly, and cover the edge cases in tests.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'I/A',
		'Attack Type': 'Token Replay',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (defects in OTP expiration verification logic)',
	},
	42: {
		'name': 'Deserializing Cryptographic Key Material Without Authenticating the Source',
		'Message': "Loading a private key (e.g. from a PEM or SSH-formatted file) without first authenticating that the input actually came from a trusted source lets an attacker who can supply that input trigger unexpected parsing behavior or supply a key of their choosing. Authenticate the source of key material before deserializing it, and validate the parsed key's type/parameters before use.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Deserialization',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (lack of authentication when deserializing PEM/SSH private keys)',
	},
	43: {
		'name': 'Using a Custom, Unvalidated Encoding Scheme in Place of a Standard One',
		'Message': "A hand-rolled encoding/framing format for cryptographic data (instead of a standard one like ASN.1/DER, JSON, or protobuf with a schema) usually skips the input validation those standard formats' parsers already provide, opening the door to malformed or adversarial input being misinterpreted. Prefer a standard, well-tested encoding with strict parsing over a custom format.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Injection',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (custom encoding schemes lacking data validation)',
	},
	44: {
		'name': 'Compressing Data Before Encryption',
		'Message': 'Compressing attacker-influenced data together with a secret before encrypting the combined result leaks information through the compressed size, because compression ratio depends on how much the secret repeats parts of the attacker-controlled input (the mechanism behind CRIME/BREACH-style attacks). Avoid compressing data that mixes a secret with attacker-controlled input prior to encryption, or compress each independently.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Compression Oracle',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (insecure data compression before encryption)',
	},
	45: {
		'name': 'Using an Insecure, Unmaintained, or Deprecated Cryptographic Library',
		'Message': 'A cryptography library with no commits or releases in years is not receiving fixes for newly discovered flaws, and its historical design may already be behind current best practice, even absent a specific known CVE. Prefer an actively maintained, widely-audited crypto library over one that has gone dormant, and check maintenance status as part of any dependency review.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'Supply Chain',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.5 (insecure or deprecated cryptographic library usage, e.g. unmaintained pyaes)',
	},
	46: {
		'name': 'Using Deprecated Cryptographic Library Threading/Locking Callback APIs',
		'Message': "Older thread-safety mechanisms for crypto libraries (such as OpenSSL's pre-1.1.0 CRYPTO_set_id_callback()/CRYPTO_set_locking_callback() pattern) have been superseded by internal thread safety and are a source of memory leaks and initialization bugs when still called against a modern library version. Remove manual locking-callback setup and rely on the library's built-in thread safety in current versions.",
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'Availability',
		'Attack Type': 'Resource Leak',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.4 (deprecated OpenSSL locking-callback functions)',
	},
	47: {
		'name': 'Skipping Required Crypto-Library Initialization or Availability Checks',
		'Message': "Using a low-level crypto engine/provider API (e.g. OpenSSL's ENGINE API) without first checking it is available, or omitting/ignoring the return value of a required initialization call (e.g. OPENSSL_init_crypto()), can leave the library in an unready state where subsequent crypto operations silently misbehave rather than failing loudly. Always check documented initialization/availability preconditions and their return values before performing crypto operations.",
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'Uninitialized State',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.8 (ENGINE API used without an availability check); CryMisTa 5.3.11 (OPENSSL_init_crypto() not properly checked)',
	},
	48: {
		'name': 'Modifying Cryptographic Security Policy at Runtime',
		'Message': 'Changing a process-wide crypto policy setting (e.g. a "crypto.policy" style configuration knob) at runtime, rather than through static configuration reviewed at deploy time, produces inconsistent and unpredictable security guarantees across the parts of the application that ran before versus after the change. Set cryptographic policy through static, reviewed configuration rather than in-process mutation.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'C/I/A',
		'Attack Type': 'Configuration Drift',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.9 (manipulation of crypto.policy at runtime)',
	},
	49: {
		'name': 'Insecure or Non-Unique Object Identifier (OID) Creation',
		'Message': "Minting a custom Object Identifier (used to name algorithms/extensions inside certificates and other crypto structures) without following the ISO/IEC 8825 and RFC 5280 rules for OID construction risks colliding with another organization's OID, causing certificates or structures to be misinterpreted or rejected downstream. Register and construct OIDs according to the standard, or reuse an existing registered OID rather than inventing one ad hoc.",
		'CWE': '',
		'Severity': 'L',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Identifier Collision',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.8 (insecure Object Identifier (OID) creation)',
	},
	50: {
		'name': 'Insecure Secret-Sharing Scheme Implementation',
		'Message': "A secret-sharing scheme (e.g. Shamir's Secret Sharing) that does not properly verify the parameters supplied by each party during share transfer/reconstruction can allow a malicious participant to bias or reconstruct the secret with fewer shares than the scheme intends to require. Validate every party's inputs against the scheme's mathematical preconditions before combining shares.",
		'CWE': '',
		'Severity': 'H',
		'Crypto Property': 'Confidentiality',
		'Attack Type': 'Secret Reconstruction',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (insecure secret-sharing mechanisms, improper verification of transfer parameters)',
	},
	51: {
		'name': 'Inadequate Error Handling While Decoding or Parsing Key Material',
		'Message': 'Swallowing, ignoring, or under-specifying errors while decoding a public key or other cryptographic structure can cause a malformed or maliciously-crafted input to be accepted as if it were valid, instead of being rejected. Treat every decode/parse failure as fatal to the operation, and avoid falling back to a default or partially-parsed value on error.',
		'CWE': '',
		'Severity': 'M',
		'Crypto Property': 'Integrity',
		'Attack Type': 'Improper Error Handling',
		'Analysis Method': '',
		'__source__': 'CryMisTa 5.3.11 (inadequate error handling in public key decoding)',
	},
	-1: {
		'name': 'UNKNOWN',
		'Message': 'UNKNOWN',
		'CWE': 'UNKNOWN',
		'Severity': 'UNKNOWN',
		'Crypto Property': 'UNKNOWN',
		'Attack Type': 'UNKNOWN',
		'Analysis Method': 'UNKNOWN',
	},
}
